- name: Wait for the pipeline to start. # This is a workaround for the pipeline not starting immediately due to another default pipeline execution
  ansible.builtin.wait_for:
    timeout: 300  # 5 minutes

- name: Trigger pipeline
  include_role:
    name: jenkins
    tasks_from: trigger-pipeline
  vars:
    usecase_group_name: "{{ gitlab_demo_srg_group }}"
    usecase_repo_name: "{{ gitlab_demo_srg_repo_name }}"
    usecase_git_ref: "main"

- name: Get pipeline status
  include_role:
    name: gitlab
    tasks_from: get-pipeline-status
  when: pipeline_id is defined
