- name: Health Check for a use case containing Gitlab
  vars:
    max_retries: 2
  block:
    - name: Wait for the pipeline to start. # This is a workaround for the pipeline not starting immediately due to another default pipeline execution
      ansible.builtin.wait_for:
        timeout: "{{ wait_before_trigger_pipeline | default(0) }}" # 0 minute in default

    - name: Increment the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: Trigger pipeline
      include_role:
        name: gitlab
        tasks_from: trigger-pipeline
      vars:
        gitlab_group_name: "{{ usecase_group_name }}"
        gitlab_repo_name: "{{ usecase_repo_name }}"
        gitlab_git_ref: "{{ usecase_git_ref }}"
      register: trigger_pipeline_result

    - name: Get pipeline status
      include_role:
        name: gitlab
        tasks_from: get-pipeline-status
      register: get_pipeline_status_result

    - name: Check GitLab pipeline result
      fail:
        msg: "GitLab pipeline failed with status: {{ get_pipeline_status_result.json.status }}"
      when: get_pipeline_status_result.json.status != 'success'
      register: check_pipeline_result

    - name: Print GitLab pipeline result
      debug:
        msg: "GitLab pipeline succeeded with status: {{ get_pipeline_status_result.json.status }}"
      when: get_pipeline_status_result.json.status == 'success'
      register: print_pipeline_result

  rescue:
    - name: Fail if maximum retries reached
      fail:
        msg: Maximum retries of health check tasks reached
      when: retry_count | int >= max_retries | int

    - name: Retry Health Check for a use case containing Gitlab
      include_tasks: usecase-health-check-gitlab.yml
      vars:
        retry_count: "{{ retry_count | default(0) }}"
        max_retries: "{{ max_retries }}"
        wait_before_trigger_pipeline: 0
        
  when: "{{ use_case_validation_tests_enabled == True | default(False) }}"