---
- name: Install dynatrace-operator via Helm (applicationMonitoring)
  kubernetes.core.helm:
    name: dynatrace-operator
    chart_ref: "oci://public.ecr.aws/dynatrace/dynatrace-operator"
    release_namespace: dynatrace
    create_namespace: true
    atomic: true
    chart_version: "{{ dt_operator_release | regex_replace('^v', '') }}"

- name: Template Dynakube manifest (applicationMonitoring)
  ansible.builtin.template:
    src: "applicationMonitoring.yaml.j2"
    dest: "{{ role_path }}/files/applicationMonitoring.yaml"
    owner: "{{ ace_box_user }}"
    group: "{{ ace_box_user }}"
    mode: "0644"

- name: Apply Dynakube manifest (applicationMonitoring)
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/applicationMonitoring.yaml"
  register: dynakube
  retries: 20
  delay: 20
  until: dynakube is not failed

- name: Install Fluent Bit (applicationMonitoring only)
  ansible.builtin.include_role:
    name: fluentbit
